// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbhtpVfyaQ9LOHDzUNVeTveSEJ-e8VmYo',
    appId: '1:500441058417:web:c22799553ee05f89dfdfd0',
    messagingSenderId: '500441058417',
    projectId: 'forest-app-65c35',
    authDomain: 'forest-app-65c35.firebaseapp.com',
    storageBucket: 'forest-app-65c35.firebasestorage.app',
    measurementId: 'G-7R5BZ6ZCFW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHplLnTIOphf8O-135R50kUsgii3F1hYY',
    appId: '1:500441058417:android:1b6d998bf1b2c0badfdfd0',
    messagingSenderId: '500441058417',
    projectId: 'forest-app-65c35',
    storageBucket: 'forest-app-65c35.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhtHJPGFMCY7wteiIgmCnDvpKJEOVKVlo',
    appId: '1:500441058417:ios:3c956d7b774c69b7dfdfd0',
    messagingSenderId: '500441058417',
    projectId: 'forest-app-65c35',
    storageBucket: 'forest-app-65c35.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhtHJPGFMCY7wteiIgmCnDvpKJEOVKVlo',
    appId: '1:500441058417:ios:3c956d7b774c69b7dfdfd0',
    messagingSenderId: '500441058417',
    projectId: 'forest-app-65c35',
    storageBucket: 'forest-app-65c35.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbhtpVfyaQ9LOHDzUNVeTveSEJ-e8VmYo',
    appId: '1:500441058417:web:8513c144b5072636dfdfd0',
    messagingSenderId: '500441058417',
    projectId: 'forest-app-65c35',
    authDomain: 'forest-app-65c35.firebaseapp.com',
    storageBucket: 'forest-app-65c35.firebasestorage.app',
    measurementId: 'G-B0SWF6MEBV',
  );

}